services:
  mysql:
    container_name: 'devweb2-av1'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=imd_market'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'